apiVersion: apps/v1
kind: Deployment
metadata:
  name: iengine
  labels:
    app: iengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iengine
  template:
    metadata:
      labels:
        app: iengine
    spec:
      containers:
        - name: iengine
          image: pbeniwal/iengine:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
